# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c0678a26dfe6fdcf22b421683294757bd37c56d39f7c45eb6db92597bb284e94e3ad0208988790a0aa9cc3979cac80cb1060a4435e7a13d8fdfaedff537e6db

test:
  secret_key_base: 75c6b2b595cb3fe180df5ffe3bb5768979af428676eee408233e69f687f3584df1052de7397f065f55735ee3c6cab57a23495eda4e24faa12c8066fb19f96d05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
